name: CI

on: push

env:
  HUGO_VERSION: '0.92.1'
  REGISTRY: ghcr.io
  IMAGE: ferdinand-beyer/hugo

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            HUGO_VERSION=${{ env.HUGO_VERSION }}
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
